########################################################################
# » LISTE DES PERMISSIONS
permissions:
  acore-use: "acore.command.use"
  acore-reload: "acore.command.reload"
  items-command: "acore.item-command.use"
  items-list: "acore.item-command.list"
  vision-use: "acore.vision.use"
  trash-use: "acore.trash.use"
  chat-command-use: "acore.chat-command.use"
  chat-bypass: "acore.chat.bypass"
  bottle-exp-use: "acore.bottlexp.use"
########################################################################

########################################################################
# » menu du /poubelle
trash-menu-name: "&ePoubelle"
# » nombre de rangés du /poubelle
trash-menu-rows: 6
########################################################################

########################################################################
# » Délai ( en secondes ) après chaque première connexion ; /bienvenue
# » Mettre à 0 si au délai voulu, les joueurs pourront /bienvenue
#   sans pression.
welcome-delay: 10
########################################################################

########################################################################
# » Bouteilles d'xp du /bottlexp ( l'item )
bottle_xp_item:
  name: "&eBouteille d'xp &7| &6%player_name%"
  glow: true
  lore:
    - "&eBouteille d'xp"
    - "&eContenant %xp% xp"
########################################################################

########################################################################
# » Détermine si la houe de farm drop les graines de blé.
farm-hoe-drops-seed: true
########################################################################

########################################################################
# » Détermine si les items ayant le tag "infinite: true" peuvent être drop.
enable-infinite-tools-drop: false
########################################################################

########################################################################
# » configurations liés au Chunk Buster.
# » délai en secondes avant la suppression du chunk
# » mettre à 0 si évènement immédiat.
delay-before-bust: 10
# » mise en place d'une animation ( true/false ) pour moins de lag.
buster-animation: true
# » s'il y a lieu de confirmation lors du placage avec un menu.
buster-menu-confirmation: true
# » nom du menu de confirmation
buster-menu-name: "&aConfirmation du Chunk Buster"
# » nombre de colonnes du menu
buster-menu-rows: 1
# » configuration du menu.
# » les termes autorisés pour 'action' sont :
#       * validate ( valide le placage )
#       * cancel ( annule le placage )
#       * none ( ne fais rien, est décoratif )
buster-menu-slots:
  0:
    material: STAINED_GLASS_PANE
    id: 5
    name: "&aValider"
    action: validate
  1:
    material: STAINED_GLASS_PANE
    id: 5
    name: "&aValider"
    action: validate
  2:
    material: STAINED_GLASS_PANE
    id: 5
    name: "&aValider"
    action: validate
  3:
    material: STAINED_GLASS_PANE
    id: 5
    name: "&aValider"
    action: validate
  4:
    material: STAINED_GLASS_PANE
    id: 15
    name: " "
    action: none
  5:
    material: STAINED_GLASS_PANE
    id: 14
    name: "&aAnnuler"
    action: cancel
  6:
    material: STAINED_GLASS_PANE
    id: 14
    name: "&aAnnuler"
    action: cancel
  7:
    material: STAINED_GLASS_PANE
    id: 14
    name: "&aAnnuler"
    action: cancel
  8:
    material: STAINED_GLASS_PANE
    id: 14
    name: "&aAnnuler"
    action: cancel
# » temps pendant lequel des particules seront affiché ( en secondes )
# » mettre 0 si aucune particule n'est voulue.
# » les particules sont créés en NMS donc cela n'impactera pas les performances du serveur :).
buster-particles-delay: 10
########################################################################
########################################################################
#                             » CHAT «
#
# » Délai minimum en seconde entre chaque message.
anti-spam-cooldown: 3
# » Maximum de majuscules par message, mettre à 0 si aucun anti-caps n'est voulu.
anti-caps-limite: 5
########################################################################

########################################################################
# » PROTECTIONS - ANTI
#
# » Mettre la liste des matériaux afin de désactiver leur craft.
anti-craft:
  - 'BEDROCK'
# » Mettre la liste des gros mots !
anti-insulte:
  - 'fdp'
  - 'connard'
  - 'fils de neuille'
  - 'salope'
# » Mettre la liste des id des potions à désactivers.
# » Pour désactiver la potion de force II il faut mettre :
anti-potions:
  STRENGTH: 2
########################################################################